import {Router} from 'express'; import {pool,query} from '../db.js';
const r=Router();
r.get('/dashboard',async(req,res,next)=>{try{const [a,b,c,d,e,f]=await Promise.all([
  query('SELECT COUNT(*)::int count FROM items'),
  query('SELECT COALESCE(SUM(stock),0)::int total FROM items'),
  query('SELECT COUNT(*)::int count FROM items WHERE stock<=min_stock'),
  query(`SELECT i.*,c.name category_name FROM items i LEFT JOIN categories c ON c.id=i.category_id WHERE stock<=min_stock ORDER BY stock ASC LIMIT 8`),
  query(`WITH calendar_days AS (SELECT generate_series(CURRENT_DATE - INTERVAL '6 days', CURRENT_DATE, INTERVAL '1 day')::date AS report_date) SELECT to_char(d.report_date,'DD Mon') AS label, COALESCE(SUM(m.quantity) FILTER (WHERE m.type='masuk'),0)::int AS masuk, COALESCE(SUM(m.quantity) FILTER (WHERE m.type='keluar'),0)::int AS keluar FROM calendar_days d LEFT JOIN stock_movements m ON m.created_at >= d.report_date AND m.created_at < d.report_date + INTERVAL '1 day' GROUP BY d.report_date ORDER BY d.report_date`),
  query(`SELECT COALESCE(c.name,'Tanpa kategori') name, COUNT(i.id)::int items, COALESCE(SUM(i.stock),0)::int stock FROM items i LEFT JOIN categories c ON c.id=i.category_id GROUP BY c.name ORDER BY stock DESC LIMIT 6`)
]);res.json({itemCount:a.rows[0].count,totalStock:b.rows[0].total,lowStockCount:c.rows[0].count,lowStock:d.rows,weeklyActivity:e.rows,categoryStock:f.rows})}catch(e){next(e)}});
r.get('/movements',async(req,res,next)=>{try{res.json((await query(`SELECT m.*,i.code item_code,i.name item_name,u.name user_name FROM stock_movements m JOIN items i ON i.id=m.item_id LEFT JOIN users u ON u.id=m.created_by ORDER BY m.created_at DESC LIMIT 100`)).rows)}catch(e){next(e)}});
r.post('/movements',async(req,res,next)=>{const client=await pool.connect();try{const {item_id,type,quantity,note}=req.body,q=Number(quantity);if(!item_id||!['masuk','keluar'].includes(type)||!Number.isInteger(q)||q<1)return res.status(400).json({message:'Data transaksi tidak valid'});await client.query('BEGIN');const item=(await client.query('SELECT * FROM items WHERE id=$1 FOR UPDATE',[item_id])).rows[0];if(!item){await client.query('ROLLBACK');return res.status(404).json({message:'Barang tidak ditemukan'})}if(type==='keluar'&&item.stock<q){await client.query('ROLLBACK');return res.status(400).json({message:'Stok tidak mencukupi'})}const delta=type==='masuk'?q:-q;await client.query('UPDATE items SET stock=stock+$1,updated_at=NOW() WHERE id=$2',[delta,item_id]);const {rows}=await client.query('INSERT INTO stock_movements(item_id,type,quantity,note,created_by) VALUES($1,$2,$3,$4,$5) RETURNING *',[item_id,type,q,note||null,req.user.id]);await client.query('COMMIT');res.status(201).json(rows[0])}catch(e){await client.query('ROLLBACK');next(e)}finally{client.release()}});
export default r;
